Cached resolver
OneSignal/pgcat pull request #1
Opened 2022-11-22 12:22 UTC by magec

Pgcat is a postgres pooler written in Rust that uses Tokio to allow concurency.

We are comparing several poolers, not only Pgcat.

The fact is that it lacks (PgCat and the rest of poolers we've seen so far) an important feature that Pgbouncer has:

In Pgbouncer (from its docu):

 >[...] Host names are resolved at connection time, the result is cached per dns_max_ttl parameter. When a host name’s resolution changes, existing server connections are automatically closed when they are released (according to the pooling mode), and new server connections immediately use the new resolution. If DNS returns several results, they are used in a round-robin manner [...].

Even though the DNS round robin is not used in our infrastructure, the DNS caching feature allow us to change read only replicas without having to restart anything.

This is a proof of concept of an implementation of such feature in PgCat. The purpose of this was to see:
- How feasible was making a contribution
- See how mature the project is

This is a proof of concept, I have tested it locally and works as expected.

2022-11-22 16:05 UTC, lilymara-onesignal requested changes
> Reviewed 7 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/pgcat/1)* status: 7 of 11 files reviewed, 2 unresolved discussions (waiting on @magec)

___
*[`Cargo.toml` line 37 at r1](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV3cd8ElB3hK3IK7NU:-NHV3cd8ElB3hK3IK7NV:bzfwuqh) ([raw file](https://github.com/onesignal/pgcat/blob/5cb61823c8b81eb4003d4ca8997616b8ea814cb2/Cargo.toml#L37)):*
> ```TOML
> phf = { version = "0.11.1", features = ["macros"] }
> exitcode = "1.1.2"
> trust-dns-resolver = "*"
> ```

Wildcard version should not be used, pin to latest version - `0.22`
___
*[`src/config.rs` line 211 at r1](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV41Dz5K2-NNtbI-ED:-NHV41Dz5K2-NNtbI-EE:b-pub3s3) ([raw file](https://github.com/onesignal/pgcat/blob/5cb61823c8b81eb4003d4ca8997616b8ea814cb2/src/config.rs#L211)):*
> ```XML
> 
>     pub fn default_dns_max_ttl() -> u64 {
> 	30
> ```

please run `cargo fmt` in the repository, there are many formatting issues and I'm having a hard time parsing the code as-written


<!-- Sent from Reviewable.io -->

2022-11-22 17:16 UTC, lilymara-onesignal requested changes
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/pgcat/1)* status: all files reviewed, 19 unresolved discussions (waiting on @magec)

___
*[`src/client.rs` line 62 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV6F5F3MylNd6GqhLL:-NHV6F5F3MylNd6GqhLM:bmrm7ud) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/client.rs#L62)):*
> ```XML
>     client_server_map: ClientServerMap,
> 
>     /// Client parameters, e.g. user, client_encoding, etc1
> ```

extra chars added to EoL
___
*[`src/client.rs` line 69 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV6H2M0W7lJ2XaPmv1:-NHV6H2M0W7lJ2XaPmv2:bmrm7ud) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/client.rs#L69)):*
> ```XML
>     stats: Reporter,
> 
>     /// Clients want to talk to admin database0
> ```

extra chars added to EoL
___
*[`src/dns_cache.rs` line 17 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVGgDs4v33shjYGCek:-NHVGgDtEUbkUZs3Q5Uv:b-jrykkp) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L17)):*
> ```XML
> #[derive(Clone, PartialEq, Debug)]
> pub struct AddrSet {
>     pub set: HashSet<IpAddr>,
> ```

field should not be public
___
*[`src/dns_cache.rs` line 21 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJfPH3L44Bm-NpxGN:-NHVGi1VDKUtn9AP6YHn:b9v7rhb) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L21)):*
> ```XML
> 
> impl AddrSet {
>     pub fn new() -> AddrSet {
> ```

fn should not be public
___
*[`src/dns_cache.rs` line 39 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJwy8-aygpYNH_yvo:-NHVJwy94Fd3rv4ZTf7K:b-pwrhyz) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L39)):*
> ```XML
> 
> //
> // A CachedResolver is dns resolution cache mechanism with customizable expiration time.
> ```

comments on items in this file should be "doc comments" - use `///` instead of `//`. This will ensure the documentation system picks them up and includes them in autogenerated documentation
___
*[`src/dns_cache.rs` line 61 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJhsb4evEIZYwSqvQ:-NHVJhsb4evEIZYwSqvR:b-jrykkp) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L61)):*
> ```XML
> pub struct CachedResolver {
>     // The configuration of the cached_resolver.
>     pub config: CachedResolverConfig,
> ```

field should not be public
___
*[`src/dns_cache.rs` line 77 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVE_k99isKSYqSM9ac:-NHVE_k99isKSYqSM9ad:biyxh2x) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L77)):*
> ```XML
> }
> 
> impl CachedResolver {
> ```

None of the functions in this struct should need to take `&mut`, since all mutations are done behind an `RwLock`. `&self` should be fine
___
*[`src/dns_cache.rs` line 95 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVGpnc6WI3Gq7lBSp_:-NHVGpnc6WI3Gq7lBSpa:bas6j51) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L95)):*
> ```XML
>         // Construct a new Resolver with default configuration options
>         let resolver = Arc::new(TokioAsyncResolver::tokio_from_system_conf()?);
>         let data = Arc::new(RwLock::new(HashMap::new()));
> ```

imo the `refresh_dns_entries_loop` fn should be private and it should be spawned here inside of the `new` fn. `new` should return an `Arc<Self>`
___
*[`src/dns_cache.rs` line 106 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVH6NI4FA9s34gl4eo:-NHVH6NJEdxcSZibfvGI:bp16t61) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L106)):*
> ```XML
>     // Schedules the refresher
>     pub async fn refresh_dns_entries_loop(&mut self) {
>         let data = self.data.clone();
> ```

clone not necessary, use `self.data` directly
___
*[`src/dns_cache.rs` line 121 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHB_wCp-zON6gP9iy:-NHVHB_wCp-zON6gP9iz:bozoar0) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L121)):*
> ```XML
> 
>             for hostname in hostnames.iter() {
>                 match CachedResolver::fetch_from_data_cache(data.clone(), hostname.as_str()) {
> ```

use `fetch_from_cache`
___
*[`src/dns_cache.rs` line 121 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVKh1w6VwYEeiw-MCY:-NHVKh1w6VwYEeiw-MCZ:b-prfawq) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L121)):*
> ```XML
> 
>             for hostname in hostnames.iter() {
>                 match CachedResolver::fetch_from_data_cache(data.clone(), hostname.as_str()) {
> ```

It's fine to use `.expect()` on this function, since hosts cannot be removed from the cache, so a hostname fetched from the list of keys on the cache is guaranteed to hold a value.
___
*[`src/dns_cache.rs` line 135 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHbr9ALOmJqK3EnQM:-NHVHbr9ALOmJqK3EnQN:bxy0f6b) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L135)):*
> ```XML
>                                     addrset, new_addrset
>                                 );
>                                 CachedResolver::store_in_cache(data.clone(), hostname, new_addrset);
> ```

ditto `&self`
___
*[`src/dns_cache.rs` line 184 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVI2QL6fjh2lRKfQGO:-NHVI2QL6fjh2lRKfQGP:bgcjwve) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L184)):*
> ```XML
>             None => {
>                 debug!("Not found, executing a dns query!");
>                 let addr_set = AddrSet::from(self.resolver.clone().lookup_ip(host).await?);
> ```

resolver clone not necessary
___
*[`src/dns_cache.rs` line 209 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHhj26rAHX6AoV9IP:-NHVHhj26rAHX6AoV9IQ:b9l6597) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L209)):*
> ```XML
>     }
> 
>     fn fetch_from_data_cache(
> ```

this function shouldn't exist,`fetch_from_cache` should be used where this function is used
___
*[`src/pool.rs` line 164 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV7CKR9t9DhjyqOOUm:-NHV7CKSAlfCWMAv-xYw:buhfqmr) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/pool.rs#L164)):*
> ```XML
>                 Err(err) => {
>                     error!("Error Starting cached_resolver error: {:?}", err);
>                     error!("Will continue without this feature");
> ```

log messages should be single events containing all relevant information, they should not be spread across two messages
___
*[`src/server.rs` line 93 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV8Rkt9hedO3qDlr1p:-NHV8Rkt9hedO3qDlr1q:bs25o91) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/server.rs#L93)):*
> ```XML
>         stats: Reporter,
>     ) -> Result<Server, Error> {
>         let addr_set = match *cached_resolver.clone() {
> ```

the two `clone`s in this block can probably be removed, can you try using `.as_ref` instead?
___
*[`src/server.rs` line 93 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVIMPb-iLDNDayuK1z:-NHVIMPb-iLDNDayuK2-:b5yh27q) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/server.rs#L93)):*
> ```XML
>         stats: Reporter,
>     ) -> Result<S [...]

2022-11-28 10:03 UTC, magec reviewed
> *[Reviewable](https://reviewable.io/reviews/onesignal/pgcat/1)* status: all files reviewed, 19 unresolved discussions (waiting on @lilymara-onesignal)

___
*[`Cargo.toml` line 37 at r1](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV3cd8ElB3hK3IK7NU:-NHxQWMZB_MbiJUBK_Bt:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/5cb61823c8b81eb4003d4ca8997616b8ea814cb2/Cargo.toml#L37)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

Wildcard version should not be used, pin to latest version - `0.22`
</blockquote></details>

Done.
___
*[`src/client.rs` line 62 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV6F5F3MylNd6GqhLL:-NHxQncP7Ci4Q9WbA3az:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/client.rs#L62)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

extra chars added to EoL
</blockquote></details>

Done.
___
*[`src/client.rs` line 69 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV6H2M0W7lJ2XaPmv1:-NHxQnutAI7YDpVAzF5C:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/client.rs#L69)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

extra chars added to EoL
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 17 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVGgDs4v33shjYGCek:-NHxR28w6IIWs6fqd7fo:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L17)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

field should not be public
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 21 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJfPH3L44Bm-NpxGN:-NHxR3u13LLY9zjnAzmG:bb6un1j) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L21)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

fn should not be public
</blockquote></details>

Done
___
*[`src/dns_cache.rs` line 39 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJwy8-aygpYNH_yvo:-NHxRNPxBav5Z62xxtL9:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L39)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

comments on items in this file should be "doc comments" - use `///` instead of `//`. This will ensure the documentation system picks them up and includes them in autogenerated documentation
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 61 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVJhsb4evEIZYwSqvQ:-NHxROs15qnD3koBxnFP:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L61)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

field should not be public
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 77 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVE_k99isKSYqSM9ac:-NHxRSD-2Q780vkv66dB:bb6mt9b) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L77)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

None of the functions in this struct should need to take `&mut`, since all mutations are done behind an `RwLock`. `&self` should be fine
</blockquote></details>

:+1:
___
*[`src/dns_cache.rs` line 95 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVGpnc6WI3Gq7lBSp_:-NHxZYggAjA1SkUb-JL6:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L95)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

imo the `refresh_dns_entries_loop` fn should be private and it should be spawned here inside of the `new` fn. `new` should return an `Arc<Self>`
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 106 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVH6NI4FA9s34gl4eo:-NHx_Nqa7b_WSkWHLyU6:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L106)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

clone not necessary, use `self.data` directly
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 121 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHB_wCp-zON6gP9iy:-NHx_OCd1rYnWxHLnGBq:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L121)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

use `fetch_from_cache`
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 121 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVKh1w6VwYEeiw-MCY:-NHxbD8I2Fkd9KW47a_g:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L121)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

It's fine to use `.expect()` on this function, since hosts cannot be removed from the cache, so a hostname fetched from the list of keys on the cache is guaranteed to hold a value.
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 135 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHbr9ALOmJqK3EnQM:-NHxciwJ2F-HDpLOIcJu:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L135)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

ditto `&self`
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 184 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVI2QL6fjh2lRKfQGO:-NHxd9g31wuZkthg_L67:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L184)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

resolver clone not necessary
</blockquote></details>

Done.
___
*[`src/dns_cache.rs` line 209 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHVHhj26rAHX6AoV9IP:-NHxdHg_13dtaOxQb5Ux:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/dns_cache.rs#L209)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

this function shouldn't exist,`fetch_from_cache` should be used where this function is used
</blockquote></details>

Done.
___
*[`src/pool.rs` line 164 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV7CKR9t9DhjyqOOUm:-NHxdP6G7PL5gtM99vfK:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/pool.rs#L164)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

log messages should be single events containing all relevant information, they should not be spread across two messages
</blockquote></details>

Done.
___
*[`src/server.rs` line 93 at r2](https://reviewable.io/reviews/onesignal/pgcat/1#-NHV8Rkt9hedO3qDlr1p:-NHxdXDK1-ziTROKPazK:b-896fix) ([raw file](https://github.com/onesignal/pgcat/blob/f310ad8b2e5dad20db32ef2b06961f19a2788538/src/server.rs#L93)):*
<details><summary><i>Previously, lilymara-onesignal (Lily Mara) wrote…</i></summary><blockquote>

the two `clone`s in this block can probably be removed, can you try using `.as_ref` instead?
</blockquote></details>

Done.
___
*[`src/server.rs` line 93 a [...]

2023-03-28 17:30 UTC, lilymara-onesignal requested changes
> Reviewed 1 of 5 files at r3, 1 of 8 files at r5, 7 of 9 files at r8, 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/pgcat/1)* status: all files reviewed, 4 unresolved discussions (waiting on @magec)

___
*[`src/dns_cache.rs` line 79 at r9](https://reviewable.io/reviews/onesignal/pgcat/1#-NRdDTeoCXAXt7bmZ8x2:-NRdDTeoCXAXt7bmZ8x3:bdrh7b3) ([raw file](https://github.com/onesignal/pgcat/blob/87a0d0f0afa6b45bd1a95035a7e4b5872f02fdba/src/dns_cache.rs#L79)):*
> ```XML
> 
>     // This is the hash that contains the hash.
>     data: Option<RwLock<HashMap<String, AddrSet>>>,
> ```

I don't see any place where `data` might be stored as `None`, so I'm not sure why this field is marked as optional
___
*[`src/dns_cache.rs` line 82 at r9](https://reviewable.io/reviews/onesignal/pgcat/1#-NRdDiws9-EF5XdBlX7m:-NRdDiws9-EF5XdBlX7n:b-12l4jf) ([raw file](https://github.com/onesignal/pgcat/blob/87a0d0f0afa6b45bd1a95035a7e4b5872f02fdba/src/dns_cache.rs#L82)):*
> ```XML
> 
>     // The resolver to be used for DNS queries.
>     resolver: Option<TokioAsyncResolver>,
> ```

Ditto, `resolver` is never `None`
___
*[`src/dns_cache.rs` line 174 at r9](https://reviewable.io/reviews/onesignal/pgcat/1#-NRdDnDY07WvzWodBjWi:-NRdDnDY07WvzWodBjWj:b-vqy13z) ([raw file](https://github.com/onesignal/pgcat/blob/87a0d0f0afa6b45bd1a95035a7e4b5872f02fdba/src/dns_cache.rs#L174)):*
> ```XML
>     // Schedules the refresher
>     async fn refresh_dns_entries_loop(&self) {
>         let resolver = TokioAsyncResolver::tokio_from_system_conf().unwrap();
> ```

Why create a resolver in this function if there's one available on `self`?
___
*[`src/errors.rs` line 16 at r8](https://reviewable.io/reviews/onesignal/pgcat/1#-NRdE2YRELp0hoZv5Q7r:-NRdE2YRELp0hoZv5Q7s:boa9jg1) ([raw file](https://github.com/onesignal/pgcat/blob/ab932a9608ef2248e8267cf35734abc04c855e17/src/errors.rs#L16)):*
> ```XML
>     TlsError,
>     StatementTimeout,
>     DNSCachedError(String),
> ```

This isn't really your problem to solve, but upstream pgcat doesn't have a great implementation of error-handling.


<!-- Sent from Reviewable.io -->

2024-03-18 12:52 UTC, nicolasvan commented
Closing this since this made it into upstream pgcat in https://github.com/postgresml/pgcat/pull/249

2024-03-18 12:52 UTC, closed without merging